import { jsPDF } from "jspdf";

export const generateReport = (result, imagePreview) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;

    // --- Header ---
    doc.setFillColor(15, 23, 42); // slate-900 (medical dark)
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("HISTOPATHOLOGY REPORT", margin, 20);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("AI-ASSISTED CANCER DETECTION SYSTEM", margin, 28);
    doc.text("CONFIDENTIAL MEDICAL RECORD", pageWidth - margin, 20, { align: "right" });

    // --- Patient / Sample Info (Mock) ---
    const today = new Date().toLocaleDateString();
    const time = new Date().toLocaleTimeString();
    const sampleId = "SMP-" + Math.floor(Math.random() * 1000000);

    doc.setTextColor(51, 65, 85); // slate-700
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("SAMPLE INFORMATION", margin, 60);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Sample ID: ${sampleId}`, margin, 70);
    doc.text(`Date: ${today}`, margin, 76);
    doc.text(`Time: ${time}`, margin, 82);
    doc.text(`Referring Physician: Dr. A. I. System`, pageWidth - margin, 70, { align: "right" });

    // --- Analysis Results ---
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("ANALYSIS RESULT", margin, 100);

    // Result Box
    const isCancer = result.prediction.toLowerCase() === "cancer";
    const boxColor = isCancer ? [254, 226, 226] : [220, 252, 231]; // Red-50 or Green-50
    const borderColor = isCancer ? [220, 38, 38] : [22, 163, 74];

    doc.setDrawColor(...borderColor);
    doc.setFillColor(...boxColor);
    doc.roundedRect(margin, 105, pageWidth - (margin * 2), 30, 3, 3, 'FD');

    doc.setFontSize(16);
    doc.setTextColor(...borderColor);
    doc.text(result.prediction.toUpperCase(), margin + 10, 122);

    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    doc.text(`Confidence Score: ${(result.confidence * 100).toFixed(1)}%`, pageWidth - margin - 10, 122, { align: "right" });

    // --- Disclaimer ---
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text("DISCLAIMER: This report is generated by an Artificial Intelligence system and is intended for screening purposes only. It does not constitute a final medical diagnosis. All results must be verified by a certified pathologist.", margin, 260, { maxWidth: pageWidth - (margin * 2) });

    // --- Footer ---
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.line(margin, 275, pageWidth - margin, 275);
    doc.text("Generated by CancerAI v1.0", margin, 282);
    doc.text(`Page 1 of 1`, pageWidth - margin, 282, { align: "right" });

    // Save
    doc.save(`Report_${sampleId}.pdf`);
};
